<a href="https://colab.research.google.com/github/vikash-mahar/DeepLearningNotes/blob/main/16BackPropagationRegression2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [ ]:
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [ ]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.get_weights()

[array([[ 0.7767874 , -1.0521739 ],
        [-0.28376108,  0.49125206]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.3010354 ],
        [0.28392613]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
new_weights=[np.array([[0.1,0.1]
                       ,[0.1,0.1]], dtype=np.float32),
             np.array([0.,0.], dtype=np.float32),
             np.array([[0.1],[0.1]], dtype=np.float32),
             np.array([0.], dtype= np.float32)]

In [ ]:
model.set_weights(new_weights)

In [ ]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
optimizer= keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [ ]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1, batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 25.6371
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 27.1790 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 24.3404 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 27.7048
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 21.7389 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 23.3673 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 23.4875 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 28.6722 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 31.0519 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 21.9173 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 24.5314 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 20.6722 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 28.2138 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 19.0584 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 18.1204
Epoch 16/75
4/4 ━━━━

In [ ]:
model.get_weights()

[array([[0.37393132, 0.37393132],
        [0.36596227, 0.36596227]], dtype=float32),
 array([0.2726632, 0.2726632], dtype=float32),
 array([[0.3732719],
        [0.3732719]], dtype=float32),
 array([0.20498694], dtype=float32)]